using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication2
{
    class SQL_COMMANDS
    {
        public static string SALES_HISTORY = "select SaleID, Product, SaleDate, CAST( StatusID AS int) as StatusID, SalePrice from [CaptureChanges].[dbo].[SalesHistory]";
        public static string CAPTURE_CHANGES_CONN = "Data Source=BRSMBVSQLDEV1;Initial Catalog=CaptureChanges;Persist Security Info=True;User ID=t-ankigu;Password=password1";
        public static string TIGER_REPL_CONN = "Data Source=BRSMBVSQLDEV1;Initial Catalog=TigerRepl;Persist Security Info=True;User ID=t-ankigu;Password=password1";
        public static string OWNER_BASE = @"SELECT
                                               [OwnerIdType]
                                              ,[OwnerId]
                                              ,[Name]
                                              ,[VersionNumber]
                                              ,[YomiName]
                                          FROM [dbo].[OwnerBase]";
                                                
        public static string OPPORTUNITY_BASE = @"SELECT 
                                                   [OpportunityId]
                                                  ,[PriceLevelId]
                                                  ,[OpportunityRatingCode]
                                                  ,[PriorityCode]
                                                  ,[Name]
                                                  ,[StepId]
                                                  ,[EstimatedValue]
                                                  ,[StepName]
                                                  ,[SalesStageCode]
                                                  ,[ParticipatesInWorkflow]
                                                  ,[PricingErrorCode]
                                                  ,[EstimatedCloseDate]
                                                  ,[CloseProbability]
                                                  ,[ActualValue]
                                                  ,[ActualCloseDate]
                                                  ,[OwningBusinessUnit]
                                                  ,[OriginatingLeadId]
                                                  ,[CreatedOn]
                                                  ,[IsPrivate]
                                                  ,[CreatedBy]
                                                  ,[ModifiedOn]
                                                  ,[ModifiedBy]
                                                  ,[VersionNumber]
                                                  ,[StateCode]
                                                  ,[StatusCode]
                                                  ,[IsRevenueSystemCalculated]
                                                  ,[CampaignId] 
                                                  ,[TransactionCurrencyId]
                                                  ,[ExchangeRate]
                                                  ,[ImportSequenceNumber]
                                                  ,[UTCConversionTimeZoneCode]
                                                  ,[TimeZoneRuleVersionNumber]
                                                  ,[OverriddenCreatedOn]
                                                  ,[ActualValue_Base]
                                                  ,[EstimatedValue_Base]
                                                  ,[TotalDiscountAmount]
                                                  ,[ModifiedOnBehalfBy]
                                                  ,[TotalAmount]
                                                  ,[CreatedOnBehalfBy]
                                                  ,[TotalAmountLessFreight]
                                                  ,[TotalLineItemDiscountAmount]
                                                  ,[CustomerId]
                                                  ,[DiscountAmount]
                                                  ,[OwnerId]
                                                  ,[FreightAmount]
                                                  ,[TotalTax]
                                                  ,[DiscountPercentage]
                                                  ,[TotalLineItemAmount] 
                                                  ,[CustomerIdName]
                                                  ,[CustomerIdType]
                                                  ,[OwnerIdType]
                                                  ,[TotalDiscountAmount_Base]
                                                  ,[FreightAmount_Base]
                                                  ,[TotalLineItemAmount_Base]
                                                  ,[TotalTax_Base]
                                                  ,[TotalLineItemDiscountAmount_Base]
                                                  ,[TotalAmount_Base]
                                                  ,[DiscountAmount_Base]
                                                  ,[TotalAmountLessFreight_Base]
                                                  ,[CustomerIdYomiName]
                                                  ,[FileDebrief]
                                                  ,[BudgetStatus]
                                                  ,[PresentProposal]
                                                  ,[SendThankYouNote]
                                                  ,[EvaluateFit]
                                                  ,[FinalDecisionDate]
                                                  ,[ConfirmInterest]
                                                  ,[CompleteInternalReview] 
                                                  ,[TimeLine]
                                                  ,[CustomerPainPoints]
                                                  ,[ResolveFeedback]
                                                  ,[PurchaseProcess]
                                                  ,[CaptureProposalFeedback]
                                                  ,[IdentifyCustomerContacts]
                                                  ,[CompleteFinalProposal]
                                                  ,[QuoteComments]
                                                  ,[BudgetAmount]
                                                  ,[ScheduleFollowup_Qualify]
                                                  ,[Need]
                                                  ,[PursuitDecision]
                                                  ,[ParentAccountId]
                                                  ,[ScheduleProposalMeeting]
                                                  ,[QualificationComments]
                                                  ,[SalesStage]
                                                  ,[ParentContactId]
                                                  ,[InitialCommunication]
                                                  ,[IdentifyPursuitTeam]
                                                  ,[ScheduleFollowup_Prospect]
                                                  ,[PurchaseTimeframe]
                                                  ,[IdentifyCompetitors]
                                                  ,[DecisionMaker]
                                                  ,[CurrentSituation]
                                                  ,[CustomerNeed]
                                                  ,[ProposedSolution]
                                                  ,[PresentFinalProposal]
                                                  ,[DevelopProposal]
                                                  ,[BudgetAmount_Base]
                                                  ,[ProcessId]
                                                  ,[StageId]
                                                  ,[mbs_opportunitylicenseprogramid]
                                                  ,[mbs_businesspriority]
                                                  ,[mbs_RCode]
                                                  ,[mbs_NotesfromPartner] 
                                                          ,[mbs_revenue]
                                                          ,[new_TimeToPurchase]
                                                          ,[mbs_subscriptionid]
                                                          ,[new_ProductId]
                                                          ,[mbs_netextendedprice]
                                                          ,[new_NoOfEmployees]
                                                          ,[mbs_billingfrequencyid]
                                                          ,[mbs_syscaltotalestrevph_Base]
                                                          ,[mbs_opportunitylicensesubtypeid]
                                                          ,[mbs_processed]
                                                          ,[new_PartnerInvolvedId]
                                                          ,[new_TotalNoOfPCs]
                                                          ,[mbs_crmrecorduniqueid]
                                                          ,[mbs_opportunitytype]
                                                          ,[mbs_processeddate]
                                                          ,[mbs_gsxopportunityid]
                                                          ,[mbs_OpportunityValue]
                                                          ,[mbs_opportunityvalue_Base]
                                                          ,[mbs_notestopartner]
                                                          ,[mbs_processedby]
                                                          ,[mbs_customerconsentflag] FROM [dbo].[OpportunityBase]";
//                                                          ,[mbs_activityinfo]
//                                                          ,[mbs_sendtogsx]
//                                                          ,[new_SalesStage]
//                                                          ,[mbs_partnerengagementtype]
//                                                          ,[mbs_gsxownerid]
//                                                          ,[new_Budget]
//                                                          ,[mbs_opportunityrouting]
//                                                          ,[mbs_contactid]
//                                                          ,[mbs_topquestionsandconcerns]
//                                                          ,[mbs_SysCalTotalEstRevPH]
//                                                          ,[mbs_EstimatedNoOfSeats]
//                                                          ,[mbs_validated]
//                                                          ,[mbs_leadqualificationreason]
//                                                          ,[mbs_mqpstatus]
//                                                          ,[mbs_promocodeid]
//                                                          ,[mbs_netextendedprice_Base]
//                                                          ,[mbs_wwlmstatus]
//                                                          ,[mbs_winlossreview] 
//                                                  ,[mbs_migrationnotes]
//                                                  ,[mbs_ForecastFlagId]
//                                                  ,[mbs_customeragreement]
//                                                  ,[mbs_internalagreement]
//                                                  ,[mbs_partnerfunding]
//                                                  ,[mbs_apengagementtypeid]
//                                            FROM [dbo].[OpportunityBase]";
                                                  //,[Description]

        public static string ACTIVITY_BASE = @"SELECT [OwningBusinessUnit]
                                                  ,[ActualEnd]
                                                  ,[VersionNumber]
                                                  ,[ActivityId] 
                                                  ,[IsBilled] 
                                                  ,[CreatedBy] 
                                                  ,[ModifiedOn]
                                                  ,[ServiceId] 
                                                  ,[ActivityTypeCode] 
                                                  ,[StateCode]
                                                  ,[ScheduledEnd]
                                                  ,[ScheduledDurationMinutes]
                                                  ,[ActualDurationMinutes]
                                                  ,[StatusCode]
                                                  ,[ActualStart]
                                                  ,[CreatedOn]
                                                  ,[PriorityCode]
                                                  ,[RegardingObjectId]
                                                  ,[Subject]
                                                  ,[IsWorkflowCreated]
                                                  ,[ScheduledStart]
                                                  ,[ModifiedBy]  
                                                  ,[RegardingObjectTypeCode]
                                                  ,[RegardingObjectIdName]
                                                  ,[TimeZoneRuleVersionNumber]
                                                  ,[UTCConversionTimeZoneCode]
                                                  ,[RegardingObjectIdYomiName]
                                                  ,[RecApptMstrOverriddenCreatedOn]
                                                  ,[RecApptMstrGlobalObjectId]
                                                  ,[SeriesStatus]
                                                  ,[RecApptMstrOutlookOwnerApptId]
                                                  ,[DeletedExceptionsList]
                                                  ,[NextExpansionInstanceDate]
                                                  ,[RecApptMstrLocation]
                                                  ,[GroupId]
                                                  ,[LastExpandedInstanceDate]
                                                  ,[ExpansionStateCode]
                                                  ,[RecApptMstrCategory]
                                                  ,[RecApptMstrIsAllDayEvent]
                                                  ,[RecApptMstrSubcategory]
                                                  ,[RecApptMstrSubscriptionId]
                                                  ,[RecApptMstrImportSequenceNumber]
                                                  ,[ModifiedFieldsMask]
                                                  ,[CreatedOnBehalfBy]
                                                  ,[OwnerId] 
                                                  ,[InstanceTypeCode]
                                                  ,[SeriesId]
                                                  ,[TransactionCurrencyId]
                                                  ,[ExchangeRate]
                                                  ,[IsRegularActivity] 
                                                  ,[OriginalStartDate]
                                                  ,[ModifiedOnBehalfBy]
                                                  ,[OwnerIdType]
                                                  ,[QteCloseOverriddenCreatedOn]
                                                  ,[QuoteNumber]
                                                  ,[QteCloseImportSequenceNumber]
                                                  ,[QteCloseCategory]
                                                  ,[QteCloseRevision]
                                                  ,[QteCloseSubcategory]
                                                  ,[ApptCategory]
                                                  ,[ApptGlobalObjectId]
                                                  ,[ApptIsAllDayEvent]
                                                  ,[ApptImportSequenceNumber]
                                                  ,[ApptOutlookOwnerApptId]
                                                  ,[ApptOverriddenCreatedOn]
                                                  ,[ApptSubcategory]
                                                  ,[ApptSubscriptionId]
                                                  ,[ApptLocation]
                                                  ,[ActualCost_Base]
                                                  ,[CampActImportSequenceNumber]
                                                  ,[BudgetedCost_Base]
                                                  ,[ActualCost] 
                                                  ,[IgnoreInactiveListMembers]
                                                  ,[DoNotSendOnOptOut]
                                                  ,[TypeCode] 
                                                  ,[CampActSubcategory]
                                                  ,[CampActOverriddenCreatedOn]
                                                  ,[ExcludeIfContactedInXDays]
                                                  ,[CampActCategory]
                                                  ,[BudgetedCost]
                                                  ,[CampActChannelTypeCode]
                                                  ,[FirstName]
                                                  ,[ReceivedOn]
                                                  ,[ResponseCode]
                                                  ,[YomiLastName]
                                                  ,[CampResOverriddenCreatedOn]
                                                  ,[YomiFirstName]
                                                  ,[CompanyName]
                                                  ,[CampResCategory]
                                                  ,[Telephone]
                                                  ,[OriginatingActivityId]
                                                  ,[Fax]
                                                  ,[LastName]
                                                  ,[CampResImportSequenceNumber]
                                                  ,[OriginatingActivityIdTypeCode]
                                                  ,[EMailAddress]
                                                  ,[CampResChannelTypeCode]
                                                  ,[YomiCompanyName]
                                                  ,[PromotionCodeName]
                                                  ,[CampResSubcategory]
                                                  ,[SuccessCount]
                                                  ,[OperationTypeCode]
                                                  ,[BulkOperationNumber]
                                                  ,[TargetMembersCount]
                                                  ,[CreatedRecordTypeCode]
                                                  ,[Parameters]
                                                  ,[ErrorNumber]
                                                  ,[TargetedRecordTypeCode]
                                                  ,[FailureCount] 
                                                  ,[Compressed]
                                                  ,[ReadReceiptRequested]
                                                  ,[DeliveryReceiptRequested]
                                                  ,[EmailSubcategory]
                                                  ,[Notifications]
                                                  ,[MessageId]
                                                  ,[Sender]
                                                  ,[ToRecipients] 
                                                  ,[EmailOverriddenCreatedOn]
                                                  ,[SubmittedBy]
                                                  ,[EmailImportSequenceNumber]
                                                  ,[EmailDirectionCode]
                                                  ,[MimeType]
                                                  ,[MessageIdDupCheck]
                                                  ,[DeliveryAttempts]
                                                  ,[TrackingToken]
                                                  ,[EmailCategory]
                                                  ,[SvcApptImportSequenceNumber]
                                                  ,[SvcApptLocation]
                                                  ,[SvcApptIsAllDayEvent]
                                                  ,[SvcApptSubcategory]
                                                  ,[SiteId]
                                                  ,[SvcApptOverriddenCreatedOn]
                                                  ,[SvcApptCategory]
                                                  ,[SvcApptSubscriptionId]
                                                  ,[TaskCategory]
                                                  ,[PercentComplete]
                                                  ,[TaskOverriddenCreatedOn]
                                                  ,[TaskSubscriptionId]
                                                  ,[TaskSubcategory]
                                                  ,[TaskImportSequenceNumber]
                                                  ,[Address]
                                                  ,[LetterImportSequenceNumber]
                                                  ,[LetterSubscriptionId]
                                                  ,[LetterCategory]
                                                  ,[LetterSubcategory]
                                                  ,[LetterDirectionCode]
                                                  ,[LetterOverriddenCreatedOn]
                                                  ,[PhoneOverriddenCreatedOn]
                                                  ,[PhoneImportSequenceNumber]
                                                  ,[PhoneNumber]
                                                  ,[PhoneSubcategory]
                                                  ,[PhoneDirectionCode]
                                                  ,[PhoneSubscriptionId]
                                                  ,[PhoneCategory]
                                                  ,[OrdCloseSubcategory]
                                                  ,[OrdCloseImportSequenceNumber]
                                                  ,[OrdCloseRevision]
                                                  ,[OrderNumber]
                                                  ,[OrdCloseCategory]
                                                  ,[OrdCloseOverriddenCreatedOn]
                                                  ,[FaxNumber]
                                                  ,[CoverPageName]
                                                  ,[NumberOfPages]
                                                  ,[FaxSubscriptionId]
                                                  ,[FaxImportSequenceNumber]
                                                  ,[BillingCode]
                                                  ,[Tsid] 
                                                  ,[FaxDirectionCode]
                                                  ,[FaxOverriddenCreatedOn]
                                                  ,[FaxSubcategory]
                                                  ,[FaxCategory]
                                                  ,[IncResSubcategory]
                                                  ,[IncResCategory]
                                                  ,[IncResImportSequenceNumber]
                                                  ,[IncResOverriddenCreatedOn]
                                                  ,[TimeSpent]
                                                  ,[CompetitorId]
                                                  ,[OppCloseOverriddenCreatedOn]
                                                  ,[OppCloseImportSequenceNumber]
                                                  ,[ActualRevenue_Base]
                                                  ,[ActualRevenue]
                                                  ,[OppCloseSubcategory]
                                                  ,[OppCloseCategory]
                                                  ,[IsMapiPrivate]
                                                  ,[LeftVoiceMail]
                                                  ,[EmailAttachmentCount]
                                                  ,[ConversationIndex]
                                                  ,[InReplyTo]
                                                  ,[CorrelationMethod]
                                                  ,[BaseConversationIndexHash]
                                                  ,[ParentActivityId]
                                                  ,[SenderMailboxId]
                                                  ,[DeliveryLastAttemptedOn]
                                                  ,[StageId]
                                                  ,[SentOn]
                                                  ,[DeliveryPriorityCode]
                                                  ,[PostponeActivityProcessingUntil]
                                                  ,[ProcessId]
                                                  ,[PostMessageType]
                                                  ,[ImportSequenceNumber]
                                                  ,[InResponseTo]
                                                  ,[PostAuthor]
                                                  ,[PostedOn]
                                                  ,[OverriddenCreatedOn]
                                                  ,[ThreadId]
                                                  ,[SocialAdditionalParams]
                                                  ,[PostURL]
                                                  ,[PostFromProfileId]
                                                  ,[SocialActivityDirectionCode]
                                                  ,[PostId] 
                                                  ,[SentimentValue]
                                                  ,[PostAuthorAccount]
                                                  ,[PostToProfileId]
                                                  ,[PostAuthorAccountName]
                                                  ,[PostAuthorAccountType]
                                                  ,[PostAuthorType]
                                                  ,[PostAuthorName]
                                                  ,[PostAuthorYomiName]
                                                  ,[PostAuthorAccountYomiName]
                                                  ,[Community]
                                                  ,[EmailSender]
                                                  ,[SendersAccount]
                                                  ,[EmailSenderObjectTypeCode]
                                                  ,[EmailSenderName]
                                                  ,[SendersAccountName]
                                                  ,[SendersAccountObjectTypeCode]
                                                  ,[EmailSenderYomiName]
                                                  ,[SendersAccountYomiName]
                                              FROM [dbo].[ActivityPointerBase]";
        //                                                  ,[Description] 

        public static string PHONE_CALL_BASE = "SELECT * FROM [dbo].[PhoneCallBase]";
        public static string PHONE_CALL_BASE_CHANGE = @"SELECT
                                                            [ActivityId],
                                                            [mbs_phonestatus],
                                                            [mbs_gsxactivityid],
                                                            [mcs_dialstarttime],
                                                            [mcs_duration],
                                                            [mcs_HoldTime],
                                                            [__$operation] [Operation],
                                                            [tran_end_time] [TransactionTime]
                                        FROM [cdc].[dbo_PhoneCallBase_CT] cdc left join [cdc].[lsn_time_mapping] tm
        	                            on cdc.[__$start_lsn] = tm.start_lsn
                                        WHERE cdc.__$operation <> 3 AND tm.tran_end_time > ";

  


        public static string ACCOUNT_BASE = @"SELECT [AccountId] 
                                      ,[AccountCategoryCode] 
                                      ,[TerritoryId] 
                                      ,[DefaultPriceLevelId]
                                      ,[CustomerSizeCode]
                                      ,[PreferredContactMethodCode]
                                      ,[CustomerTypeCode]
                                      ,[AccountRatingCode]
                                      ,[IndustryCode]
                                      ,[TerritoryCode]
                                      ,[AccountClassificationCode]
                                      ,[BusinessTypeCode]
                                      ,[OwningBusinessUnit]
                                      ,[OriginatingLeadId]
                                      ,[PaymentTermsCode]
                                      ,[ShippingMethodCode]
                                      ,[PrimaryContactId]
                                      ,[ParticipatesInWorkflow]
                                      ,[Name] 
                                      ,[AccountNumber]
                                      ,[Revenue]
                                      ,[NumberOfEmployees]
                                      ,[Description]
                                      ,[SIC]
                                      ,[OwnershipCode]
                                      ,[MarketCap]
                                      ,[SharesOutstanding]
                                      ,[TickerSymbol]
                                      ,[StockExchange]
                                      ,[WebSiteURL]
                                      ,[FtpSiteURL]
                                      ,[EMailAddress1]
                                      ,[EMailAddress2]
                                      ,[EMailAddress3]
                                      ,[DoNotPhone]
                                      ,[DoNotFax]
                                      ,[Telephone1]
                                      ,[DoNotEMail]
                                      ,[Telephone2]
                                      ,[Fax]
                                      ,[Telephone3]
                                      ,[DoNotPostalMail]
                                      ,[DoNotBulkEMail]
                                      ,[DoNotBulkPostalMail]
                                      ,[CreditLimit]
                                      ,[CreditOnHold]
                                      ,[IsPrivate]
                                      ,[CreatedOn] 
                                      ,[CreatedBy]
                                      ,[ModifiedOn]
                                      ,[ModifiedBy]
                                      ,[VersionNumber] 
                                      ,[ParentAccountId]
                                      ,[Aging30]
                                      ,[StateCode]
                                      ,[Aging60]
                                      ,[StatusCode]
                                      ,[Aging90]
                                      ,[PreferredAppointmentDayCode]
                                      ,[PreferredSystemUserId]
                                      ,[PreferredAppointmentTimeCode]
                                      ,[Merged]
                                      ,[DoNotSendMM]
                                      ,[MasterId]
                                      ,[LastUsedInCampaign]
                                      ,[PreferredServiceId]
                                      ,[PreferredEquipmentId]
                                      ,[ExchangeRate]
                                      ,[UTCConversionTimeZoneCode]
                                      ,[OverriddenCreatedOn]
                                      ,[TimeZoneRuleVersionNumber]
                                      ,[ImportSequenceNumber]
                                      ,[TransactionCurrencyId]
                                      ,[CreditLimit_Base]
                                      ,[Aging30_Base]
                                      ,[Revenue_Base]
                                      ,[Aging90_Base]
                                      ,[MarketCap_Base]
                                      ,[Aging60_Base]
                                      ,[YomiName]
                                      ,[OwnerId]
                                      ,[ModifiedOnBehalfBy]
                                      ,[CreatedOnBehalfBy]
                                      ,[OwnerIdType]
                                      ,[EntityImageId]
                                      ,[ProcessId]
                                      ,[StageId]
                                      ,[new_ManagedTerritory]
                                      ,[new_AccountTS]
                                      ,[mbs_SalesDistrictId]
                                      ,[mbs_stateid]
                                      ,[mbs_serverstotal]
                                      ,[new_ATUName]
                                      ,[new_Industry]
                                      ,[mbs_tenantid]
                                      ,[mbs_crmrecorduniqueid]
                                      ,[new_CRMServerLicenses]
                                      ,[mbs_Segment]
                                      ,[mbs_SalesSubDistrictId]
                                      ,[mbs_LeadCountry]
                                      ,[new_ATUGroupName]
                                      ,[mbs_hierarchylevelid]
                                      ,[mbs_pcdevicestotal]
                                      ,[new_Vertical]
                                      ,[new_VerticalCategory]
                                      ,[mbs_StateProvidence]
                                      ,[new_SubSegment]
                                      ,[new_Segment]
                                      ,[mbs_itbudget_Base]
                                      ,[mbs_msorgid]
                                      ,[mbs_SubSegment]
                                      ,[new_AccountManager]
                                      ,[mbs_countryid]
                                      ,[new_ManagedVertical]
                                      ,[mbs_industryid]
                                      ,[mbs_itbudget]
                                      ,[mbs_mioid]
                                      ,[new_MSSalesTPID]
                                      ,[new_CRMUserLicences]
                                      ,[mbs_fiscalcalendarstart]
                                      ,[new_GSXAccountID]
                                      ,[mbs_dunsnumber]
                                      ,[mbs_pccounttotalorg]
                                      ,[new_ATUManager]
                                      ,[mbs_TaxID]
                                  FROM [dbo].[AccountBase]";
    }
}
